LIBRARY_NAME = Toggle
Toggle_INSTALL_PATH = /var/mobile/Library/SBSettings/Toggles/Tether/
Toggle_OBJC_FILES = Toggle.m
Toggle_FRAMEWORKS = Foundation UIKit CoreGraphics
Toggle_PRIVATE_FRAMEWORKS = Preferences

ADDITIONAL_CFLAGS = -std=c99

include framework/makefiles/common.mk
include framework/makefiles/library.mk
